; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
; 设置ESP32-S3 CPU频率为240MHz
board_build.f_cpu = 240000000L
; 排除StepperControl.cpp文件，避免编译错误
build_src_filter = +<*> -<StepperControl.cpp>
; 添加Web服务器所需的库
lib_deps = 
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    adafruit/Adafruit NeoPixel@^1.10.5
